### PR TITLE
Added nelson-gui to nelson installations

### PR DESCRIPTION
**Pull request by nuriel77**
Adding nelson gui to installations of nelson
https://github.com/nuriel77/iri-playbook/issues/68

### CODE REVIEW

**Comment by nuriel77** [comment]
Can't say I am too happy about this. I am considering not to add this after all.
The installation works flawlessly on Ubuntu, having troubles on CentOS (my test servers have only 2GB memory), node-gyp hanging and eating up alll memory and CPU during installation.

I think this is better left for people to install manually, and not overload the playbook installer too much.

**Comment by svenger87** [comment]
I´d love to see this added :)

**Comment by nuriel77** [comment]
Upgraded test machine to 4 GB mem, 4 cores, on CentOS this is hanging when trying to install nelson-gui via Ansible npm module:
```sh
22882 nobody    20   0 1463772 584560  12504 S 100.3 15.1   4:05.29 node-gyp
```

I am afraid I cannot merge until I get some time to see what's wrong and resolve this.

**Comment by nuriel77** [comment]
Think I found how to work around this... Install node-gyp before nelson-gui seems to do the trick. Running some more tests.

**Comment by nuriel77** [comment]
Ok merging the latest change. The problem was installing the package as root. Installing as user on the other hand creates other permission errors. Would probably need to create a custom path where to install things, but since I am not too experienced with the proper way how to install nodejs packages (and spending too much time on it anyway) I am letting this pass with `--unsafe-perm` flag.

Once the gui is opened in the browser, the user will have to set the user:password on the URL as stated in the nelson.gui docs https://github.com/SemkoDev/nelson.gui#connecting-to-nelson-v040-with-usernamepassword 
I requested if this can be handled differently to be more compatible with reverse proxies.

**Comment by svenger87** [comment]
Enabled it via latest iric. Working great :)

**Pull request merged**
